### ISSUE TITLE
json gem is missing

### ISSUE THREAD

**Issue by emj365** [sleede/fab-manager#73] opened 2017-06-27 10:45 UTC
After bundle still got `json` missing.
Fixed after adding `gem 'json', '~> 1.8'` to Gemfile.

**Comment by sylvainbx** [comment] 2017-06-29 08:04
I'm sorry but I cannot reproduce this issue. Please, can you specify which version you're using (v2.x.x / dev / master) AND which method (docker / docker-compose / from sources)?

**Comment by sylvainbx** [comment] 2017-09-18 11:12
Closing this as it isn't reproductible yet, and the needed infos were not provided. Feel free to re-open it, providing more infos.

**Closed as completed by sylvainbx** 2017-09-18 11:12 UTC
Labels: unable to reproduce
